#!/usr/bin/env bash
# Pages CMS - Setup script using gh CLI
# Creates GitHub App (opens browser) and writes .env with generated values
#
# Expects Pages CMS to be reachable via Cloudflare tunnel at CMS_DOMAIN.
# The main n8n stack's cloudflared service handles routing.

set -e
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# Default domain -- override by setting CMS_DOMAIN env var
CMS_DOMAIN="${CMS_DOMAIN:-cms.panditai.org}"

# If only PEM path passed, just add private key to existing .env
if [[ -n "$1" && -f "$1" && -z "$2" ]]; then
  if [[ ! -f .env ]]; then
    echo "Error: .env not found. Run ./setup.sh first."
    exit 1
  fi
  echo "Adding private key from $1 to .env ..."
  python3 -c "
import re, sys
key = open(sys.argv[1]).read().strip().replace('\n', '\\\\n')
env = open('.env').read()
env = re.sub(r'^GITHUB_APP_PRIVATE_KEY=.*$', 'GITHUB_APP_PRIVATE_KEY=\"' + key + '\"', env, flags=re.MULTILINE)
open('.env', 'w').write(env)
" "$1"
  echo "Done. Run: docker compose up --build"
  exit 0
fi

# Check gh is installed and authenticated
if ! command -v gh &>/dev/null; then
  echo "Error: gh CLI not found. Install from https://cli.github.com/"
  exit 1
fi

if ! gh auth status &>/dev/null; then
  echo "Error: Not logged in to gh. Run: gh auth login"
  exit 1
fi

# Generate secrets
CRYPTO_KEY=$(openssl rand -base64 32)
CRON_SECRET=$(openssl rand -base64 32)
WEBHOOK_SECRET=$(openssl rand -base64 32)

CALLBACK_URL="https://${CMS_DOMAIN}/api/auth/github"
WEBHOOK_URL="https://${CMS_DOMAIN}/api/webhook/github"

# Pre-filled GitHub App creation URL for Pages CMS
GITHUB_APP_URL="https://github.com/settings/apps/new?name=Pages%20CMS&description=CMS%20for%20static%20sites&url=https://pagescms.org&callback_urls[]=$(python3 -c "import urllib.parse; print(urllib.parse.quote('${CALLBACK_URL}', safe=''))")&request_oauth_on_install=true&public=false&administration=write&contents=write&metadata=read&webhook_active=true&webhook_url=$(python3 -c "import urllib.parse; print(urllib.parse.quote('${WEBHOOK_URL}', safe=''))")&events[]=installation&events[]=repository&events[]=push&events[]=delete"

echo "Opening GitHub App creation page..."
echo ""
echo "Pre-filled values:"
echo "  Callback URL:  ${CALLBACK_URL}"
echo "  Webhook URL:   ${WEBHOOK_URL}"
echo "  Webhook secret: ${WEBHOOK_SECRET}"
echo ""

if command -v open &>/dev/null; then
  open "$GITHUB_APP_URL"
elif command -v xdg-open &>/dev/null; then
  xdg-open "$GITHUB_APP_URL"
else
  echo "Open this URL: $GITHUB_APP_URL"
fi

echo "Set the Webhook secret to the value above when creating the app."
echo ""

# Write .env
cat > .env << EOF
# Pages CMS - Generated by setup.sh

BASE_URL=https://${CMS_DOMAIN}
CRYPTO_KEY=$CRYPTO_KEY
CRON_SECRET=$CRON_SECRET
GITHUB_APP_WEBHOOK_SECRET=$WEBHOOK_SECRET

GITHUB_APP_ID=
GITHUB_APP_NAME=
GITHUB_APP_CLIENT_ID=
GITHUB_APP_CLIENT_SECRET=
GITHUB_APP_PRIVATE_KEY=

RESEND_API_KEY=
RESEND_FROM_EMAIL=onboarding@resend.dev
EOF

echo "Created .env (BASE_URL=https://${CMS_DOMAIN})."
echo ""
echo "After creating the GitHub App:"
echo "  1. Edit .env: add GITHUB_APP_ID, GITHUB_APP_NAME, GITHUB_APP_CLIENT_ID, GITHUB_APP_CLIENT_SECRET"
echo "  2. Add private key: ./setup.sh /path/to/your-app.pem"
echo "  3. Add RESEND_API_KEY from resend.com"
echo ""
echo "Then: docker compose up --build"
