/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardSqlReplRouteImport } from './routes/_dashboard.sql-repl'
import { Route as DashboardMemoryBlocksRouteImport } from './routes/_dashboard.memory-blocks'
import { Route as DashboardEntitiesRouteImport } from './routes/_dashboard.entities'
import { Route as DashboardDashboardRouteImport } from './routes/_dashboard.dashboard'
import { Route as DashboardAboutRouteImport } from './routes/_dashboard.about'

const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSqlReplRoute = DashboardSqlReplRouteImport.update({
  id: '/sql-repl',
  path: '/sql-repl',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMemoryBlocksRoute = DashboardMemoryBlocksRouteImport.update({
  id: '/memory-blocks',
  path: '/memory-blocks',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEntitiesRoute = DashboardEntitiesRouteImport.update({
  id: '/entities',
  path: '/entities',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDashboardRoute = DashboardDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAboutRoute = DashboardAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof DashboardAboutRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/entities': typeof DashboardEntitiesRoute
  '/memory-blocks': typeof DashboardMemoryBlocksRoute
  '/sql-repl': typeof DashboardSqlReplRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof DashboardAboutRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/entities': typeof DashboardEntitiesRoute
  '/memory-blocks': typeof DashboardMemoryBlocksRoute
  '/sql-repl': typeof DashboardSqlReplRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_dashboard/about': typeof DashboardAboutRoute
  '/_dashboard/dashboard': typeof DashboardDashboardRoute
  '/_dashboard/entities': typeof DashboardEntitiesRoute
  '/_dashboard/memory-blocks': typeof DashboardMemoryBlocksRoute
  '/_dashboard/sql-repl': typeof DashboardSqlReplRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard'
    | '/entities'
    | '/memory-blocks'
    | '/sql-repl'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dashboard'
    | '/entities'
    | '/memory-blocks'
    | '/sql-repl'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/_dashboard/about'
    | '/_dashboard/dashboard'
    | '/_dashboard/entities'
    | '/_dashboard/memory-blocks'
    | '/_dashboard/sql-repl'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/sql-repl': {
      id: '/_dashboard/sql-repl'
      path: '/sql-repl'
      fullPath: '/sql-repl'
      preLoaderRoute: typeof DashboardSqlReplRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/memory-blocks': {
      id: '/_dashboard/memory-blocks'
      path: '/memory-blocks'
      fullPath: '/memory-blocks'
      preLoaderRoute: typeof DashboardMemoryBlocksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/entities': {
      id: '/_dashboard/entities'
      path: '/entities'
      fullPath: '/entities'
      preLoaderRoute: typeof DashboardEntitiesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard': {
      id: '/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/about': {
      id: '/_dashboard/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof DashboardAboutRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAboutRoute: typeof DashboardAboutRoute
  DashboardDashboardRoute: typeof DashboardDashboardRoute
  DashboardEntitiesRoute: typeof DashboardEntitiesRoute
  DashboardMemoryBlocksRoute: typeof DashboardMemoryBlocksRoute
  DashboardSqlReplRoute: typeof DashboardSqlReplRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAboutRoute: DashboardAboutRoute,
  DashboardDashboardRoute: DashboardDashboardRoute,
  DashboardEntitiesRoute: DashboardEntitiesRoute,
  DashboardMemoryBlocksRoute: DashboardMemoryBlocksRoute,
  DashboardSqlReplRoute: DashboardSqlReplRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
